package main

import "html/template"

var pageTpl = template.Must(template.New("page").Parse(pageHTML))

const pageHTML = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{.Title}}</title>
<style>
:root{--bg:#0a0f1a;--panel:#111827;--card:#151f32;--line:#263348;--muted:#718096;--text:#e2e8f0;--blue:#3b82f6;--green:#22c55e;--red:#ef4444;--orange:#f59e0b;--purple:#8b5cf6}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#0f172a 0,#0a0f1a 40%);font-family:'Inter',system-ui,-apple-system,BlinkMacSystemFont,sans-serif;color:var(--text);font-size:14px;min-height:100vh}
.header{display:flex;align-items:center;justify-content:space-between;padding:18px 24px;border-bottom:1px solid var(--line);background:rgba(15,23,42,.85);backdrop-filter:blur(12px);position:sticky;top:0;z-index:10}
.logo{display:flex;align-items:center;gap:12px}.logo h1{margin:0;font-size:18px;font-weight:800;background:linear-gradient(135deg,#3b82f6,#8b5cf6);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.logo small{color:var(--muted);font-size:12px}
.meta{display:flex;align-items:center;gap:16px;color:var(--muted);font-size:12px}.meta span{display:flex;align-items:center;gap:6px}
.meta .dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 10px rgba(34,197,94,.4)}.nav{display:flex;gap:6px;margin-left:auto}.nav button{border:0;background:transparent;color:var(--muted);padding:9px 14px;border-radius:10px;font-size:13px;cursor:pointer;transition:.15s}.nav button:hover{background:rgba(255,255,255,.06);color:var(--text)}.nav button.active{background:rgba(59,130,246,.15);color:var(--blue)}
.main{padding:20px;max-width:1600px;margin:auto}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.stat{background:rgba(17,24,39,.9);border:1px solid var(--line);border-radius:18px;padding:18px;display:flex;align-items:center;gap:14px}.stat .icon{width:44px;height:44px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:20px}.stat .icon.blue{background:rgba(59,130,246,.15);color:var(--blue)}.stat .icon.green{background:rgba(34,197,94,.15);color:var(--green)}.stat .icon.red{background:rgba(239,68,68,.15);color:var(--red)}.stat .icon.orange{background:rgba(245,158,11,.15);color:var(--orange)}.stat .text .num{font-size:24px;font-weight:800}.stat .text .label{color:var(--muted);font-size:12px}
.layout{display:grid;grid-template-columns:minmax(460px,1.1fr) minmax(460px,.9fr);gap:18px}.left{display:grid;gap:18px}.right{display:grid;gap:18px}
.card{background:rgba(17,24,39,.95);border:1px solid var(--line);border-radius:20px;padding:20px;box-shadow:0 8px 30px rgba(0,0,0,.25)}.card h2{margin:0 0 16px;font-size:17px;font-weight:700;display:flex;align-items:center;gap:8px}.card h2::before{content:'';width:4px;height:16px;background:linear-gradient(180deg,var(--blue),var(--purple));border-radius:999px}
.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px 14px}.full{grid-column:1/-1}label{display:block;margin:0 0 5px;color:#a0aec0;font-size:12px;font-weight:650}input,textarea,select{width:100%;border:1px solid #334155;background:#0d1321;color:var(--text);border-radius:11px;padding:10px 12px;outline:none;transition:.15s;font-size:13px}input:focus,textarea:focus,select:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(59,130,246,.1)}textarea{min-height:100px;resize:vertical}
.checks{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.check{display:flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:999px;padding:7px 10px;background:#0d1321;color:#cbd5e1;font-size:12px}.check input{width:auto}
.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.btn{border:0;border-radius:11px;padding:10px 14px;background:#1e293b;color:var(--text);cursor:pointer;font-weight:700;font-size:13px;transition:.15s}.btn:hover{filter:brightness(1.1)}.primary{background:linear-gradient(135deg,#2563eb,#3b82f6)}.ok{background:linear-gradient(135deg,#15803d,#22c55e)}.danger{background:linear-gradient(135deg,#b91c1c,#ef4444)}.ghost{background:#0d1321;border:1px solid var(--line)}.btn:disabled{opacity:.5;cursor:not-allowed}
.statusbox{border:1px solid var(--line);background:#0d1321;border-radius:14px;padding:14px}.statusbox .conn{font-size:13px}.statusbox .conn .badge{display:inline-block;padding:3px 8px;border-radius:999px;font-size:11px;margin-left:8px}.badge.ok{background:rgba(34,197,94,.15);color:var(--green)}.badge.bad{background:rgba(239,68,68,.15);color:var(--red)}
.perms{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.pill{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:11px;background:#1e3a5f;color:#93c5fd}.pill.okp{background:#064e3b;color:#86efac}.pill.badp{background:#450a0a;color:#fca5a5}
.browserbar{display:grid;grid-template-columns:1fr auto auto auto;gap:6px;margin-bottom:10px}.dirlist{max-height:320px;overflow:auto;border:1px solid var(--line);border-radius:14px;background:#0d1321}.dirlist::-webkit-scrollbar{width:6px}.dirlist::-webkit-scrollbar-track{background:#0d1321}.dirlist::-webkit-scrollbar-thumb{background:#334155;border-radius:999px}
table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #1e293b;padding:9px;text-align:left;font-size:12px;vertical-align:top}th{color:#94a3b8;background:#111827;position:sticky;top:0}tr:last-child td{border-bottom:0}tr:hover{background:rgba(255,255,255,.03)}
.result{min-height:120px}.oktxt{color:var(--green)}.badtxt{color:var(--red)}.warn{color:var(--orange)}pre{white-space:pre-wrap;max-height:300px;overflow:auto;background:#060a12;border:1px solid var(--line);padding:14px;border-radius:14px;font-size:12px;color:#94a3b8}
.toast{position:fixed;right:20px;bottom:20px;background:#052e16;color:#dcfce7;border:1px solid #166534;border-radius:14px;padding:12px 16px;box-shadow:0 12px 30px rgba(0,0,0,.35);display:none;z-index:100}.toast.bad{background:#450a0a;color:#fee2e2;border-color:#991b1b}
.tasklist{max-height:180px;overflow:auto;border:1px solid var(--line);border-radius:14px;background:#0d1321;padding:8px}.taskitem{display:flex;align-items:center;justify-content:space-between;padding:7px 10px;border-radius:9px;margin-bottom:4px;background:rgba(255,255,255,.02);font-size:12px;color:#cbd5e1}.taskitem:hover{background:rgba(255,255,255,.06)}.taskitem .del{color:var(--muted);cursor:pointer;font-size:14px}.taskitem .del:hover{color:var(--red)}
@media(max-width:1100px){.stats{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}.browserbar{grid-template-columns:1fr 1fr}}
@media(max-width:640px){.header{padding:14px}.main{padding:12px}.stats{grid-template-columns:1fr}.formgrid{grid-template-columns:1fr}.browserbar{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="header"><div class="logo"><h1>NetDrive Sweeper</h1><small>CloudDrive2 gRPC 清理工具</small></div><div class="meta"><span><span class="dot"></span>运行中</span><span>v2.0</span></div><nav class="nav"><button class="active" data-tab="config">配置</button><button data-tab="browser">目录</button><button data-tab="result">结果</button><button data-tab="logs">日志</button></nav></div>
<main class="main">
<div class="stats"><div class="stat"><div class="icon blue">📡</div><div class="text"><div class="num" id="statChecked">0</div><div class="label">检查文件</div></div></div><div class="stat"><div class="icon orange">🔍</div><div class="text"><div class="num" id="statMatched">0</div><div class="label">命中垃圾</div></div></div><div class="stat"><div class="icon green">🗑️</div><div class="text"><div class="num" id="statDeleted">0</div><div class="label">已删除</div></div></div><div class="stat"><div class="icon red">⚠️</div><div class="text"><div class="num" id="statErrors">0</div><div class="label">错误</div></div></div></div>
<div class="layout">
<div class="left">
<section class="card" id="config"><h2>连接与规则</h2><div class="formgrid"><div class="full"><label>CD2 gRPC 地址</label><input id="address" placeholder="192.168.10.252:19798"></div><div class="full"><label>API Token</label><input id="token" type="password" autocomplete="off"></div><div><label>广告后缀</label><input id="adExts"></div><div><label>视频后缀</label><input id="videoExts"></div><div><label>小视频阈值 MB</label><input id="sizeLimit" type="number" step="0.1"></div><div><label>最大深度，0 不限制</label><input id="maxDepth" type="number"></div><div class="full"><label>排除目录关键词</label><input id="excludeDirs"></div><div class="full"><label>扫描延迟 ms</label><input id="scanDelay" type="number"></div><input id="tasksHidden" type="hidden"></div><div class="checks"><label class="check"><input id="forceRefresh" type="checkbox">强制刷新 CD2 缓存</label><label class="check"><input id="offlineOnly" type="checkbox">只清理已完成离线任务目录</label><label class="check"><input id="deletePermanently" type="checkbox">永久删除</label></div><div class="full"><label>清理目录（支持多选）</label><div class="tasklist" id="taskList"></div><div class="actions" style="margin-top:10px"><button class="btn ghost" id="clearTasksBtn">清空目录</button></div></div><div class="actions"><button class="btn primary" id="saveBtn">保存配置</button><button class="btn" id="testBtn">测试 Token</button><button class="btn ok" id="scanBtn">扫描预览</button><button class="btn danger" id="cleanBtn">执行清理</button></div></section>
<section class="card" id="result"><h2>扫描结果</h2><div id="resultBox" class="result muted">暂无扫描结果</div></section>
</div>
<div class="right">
<section class="card"><h2>Token 状态</h2><div id="status" class="statusbox">加载中...</div><div id="perms" class="perms"></div></section>
<section class="card" id="browser"><h2>目录浏览</h2><div class="browserbar"><input id="browsePath" value="/"><button class="btn" id="listBtn">加载</button><button class="btn ok" id="addCurrentBtn">加入当前</button><button class="btn" id="addAllBtn">加入子目录</button></div><div style="color:var(--muted);font-size:12px;margin-bottom:10px">浏览到完成的离线任务目录后加入清理；支持多选目录。</div><div id="dirs" class="dirlist"><table><tr><td class="muted">点击"加载"浏览目录</td></tr></table></div></section>
<section class="card" id="logs"><div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px"><h2 style="margin:0">运行日志</h2><div class="actions" style="margin:0"><button class="btn ghost" id="logsBtn">刷新</button><button class="btn danger" id="clearLogsBtn">清空</button></div></div><pre id="logsBox"></pre></section>
</div>
</div>
</main><div id="toast" class="toast"></div>
<script>
let state={};
async function api(url,opt){let r=await fetch(url,{cache:'no-store',headers:{'Content-Type':'application/json'},...(opt||{})});let j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||'请求失败');return j}
function el(id){return document.getElementById(id)}function val(id){return el(id).value}function setv(id,v){el(id).value=v??''}function checked(id){return el(id).checked}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg,bad){let t=el('toast');t.textContent=msg;t.className='toast'+(bad?' bad':'');t.style.display='block';setTimeout(()=>t.style.display='none',2800)}
function taskList(){return val('tasksHidden').split('\n').map(x=>x.trim()).filter(Boolean)}
function setTaskList(list){setv('tasksHidden',list.join('\n'));renderTaskList(list)}
function renderTaskList(list){if(!list||!list.length){el('taskList').innerHTML='<div style="text-align:center;color:var(--muted);padding:14px">尚未添加清理目录</div>';return}el('taskList').innerHTML=list.map(p=>'<div class="taskitem"><span>'+esc(p)+'</span><span class="del" onclick="removeTask('+JSON.stringify(p)+')">×</span></div>').join('')}
function removeTask(p){let t=taskList();t=t.filter(x=>x!==p);setTaskList(t)}
function fillConfig(c){setv('address',c.address);setv('token',c.token);setv('adExts',c.ad_exts);setv('videoExts',c.video_exts);setv('sizeLimit',c.size_limit_mb);setv('excludeDirs',c.exclude_dirs);setv('scanDelay',c.scan_delay_ms);setv('maxDepth',c.max_depth);setTaskList(c.tasks&&c.tasks.length?c.tasks:['/']);el('forceRefresh').checked=!!c.force_refresh;el('offlineOnly').checked=c.offline_only!==false;el('deletePermanently').checked=!!c.delete_permanently}
async function load(){let j=await api('/api/state?_='+Date.now());state=j;fillConfig(j.config);renderStatus(j.status);loadLogs().catch(()=>{})}
function renderStatus(s){let st=el('status');st.innerHTML='<div class="conn">'+esc(s.last_message||'未连接')+'</div>';let t=s.token;if(!t){el('perms').innerHTML='<span class="pill">尚未读取 TokenInfo</span>';return}st.innerHTML='<div class="conn">根目录：<b>'+esc(t.rootDir)+'</b><span class="badge ok">已连接</span></div><div style="color:var(--muted);font-size:12px;margin-top:6px">名称：'+esc(t.friendlyName||'-')+'</div>';let p=[['allow_list',t.allowList],['allow_delete',t.allowDelete],['allow_delete_permanently',t.allowDeletePermanently]];el('perms').innerHTML=p.map(x=>'<span class="pill '+(x[1]?'okp':'badp')+'">'+x[0]+' '+(x[1]?'OK':'NO')+'</span>').join('')}
async function saveCfg(){let c={address:val('address'),token:val('token'),ad_exts:val('adExts'),video_exts:val('videoExts'),size_limit_mb:parseFloat(val('sizeLimit')||0),exclude_dirs:val('excludeDirs'),scan_delay_ms:parseInt(val('scanDelay')||0),max_depth:parseInt(val('maxDepth')||0),force_refresh:checked('forceRefresh'),offline_only:checked('offlineOnly'),delete_permanently:checked('deletePermanently'),tasks:taskList()};let j=await api('/api/save',{method:'POST',body:JSON.stringify(c)});if(j.config)fillConfig(j.config);toast('配置已保存')}
async function testConn(){try{await saveCfg();let j=await api('/api/test?_='+Date.now());renderStatus({last_message:j.message,token:j.token});el('resultBox').innerHTML='<span class="oktxt">'+esc(j.message)+'</span>'}catch(e){toast(e.message,true);el('resultBox').innerHTML='<span class="badtxt">'+esc(e.message)+'</span>'}}
async function listDir(){try{let path=val('browsePath')||'/';let j=await api('/api/list?path='+encodeURIComponent(path)+'&_='+Date.now());renderStatus({last_message:'目录加载成功 '+j.displayPath,token:j.token});let rows=[];if(path!='/'){let up=path.split('/').slice(0,-1).join('/')||'/';rows.push('<tr><td>..</td><td><button class="btn enter" data-path="'+esc(up)+'">返回上级</button></td></tr>')}for(let d of j.dirs){rows.push('<tr><td><input type="checkbox" class="dirchk" data-path="'+esc(d.path)+'" style="margin-right:8px">'+esc(d.displayPath)+'</td><td><button class="btn enter" data-path="'+esc(d.path)+'" style="margin-right:6px">进入</button><button class="btn ok add" data-path="'+esc(d.path)+'">加入</button></td></tr>')}el('dirs').innerHTML='<table><tr><th style="width:18px"></th><th style="flex:1">目录</th><th>操作</th></tr>'+rows.join('')+'</table>';document.querySelectorAll('.enter').forEach(b=>b.onclick=function(){setv('browsePath',this.dataset.path);listDir()});document.querySelectorAll('.add').forEach(b=>b.onclick=function(){addTask(this.dataset.path)});document.querySelectorAll('.dirchk').forEach(c=>c.onchange=updateAddAll)}catch(e){el('dirs').innerHTML='<table><tr><td colspan="2" class="badtxt">'+esc(e.message)+'</td></tr></table>'}}
function updateAddAll(){let checked=document.querySelectorAll('.dirchk:checked');el('addAllBtn').textContent=checked.length?'加入选中 ('+checked.length+')':'加入子目录'}
function addTask(p){let t=taskList();if(!t.includes(p))t.push(p);setTaskList(t);toast('已加入清理目录')}
function addAllTasks(){let checked=document.querySelectorAll('.dirchk:checked');if(!checked.length){let inputs=document.querySelectorAll('.dirchk');inputs.forEach(i=>i.checked=true);checked=inputs}checked.forEach(c=>addTask(c.dataset.path));toast('已加入选中目录')}
function clearTasks(){setTaskList([]);toast('已清空清理目录')}
async function scan(del){try{await saveCfg();let j=await api(del?'/api/clean':'/api/scan');el('statChecked').textContent=j.checked;el('statMatched').textContent=j.matched;el('statDeleted').textContent=j.deleted;el('statErrors').textContent=j.errors?j.errors.length:0;let h='<div style="border:1px solid var(--line);background:#0d1321;border-radius:14px;padding:14px;margin-bottom:16px">检查 <b>'+j.checked+'</b>，命中 <b>'+j.matched+'</b>，删除 <b>'+j.deleted+'</b></div>';if(j.offlineTasks&&j.offlineTasks.length){h+='<h3 style="font-size:14px;margin:16px 0 10px">离线任务目录状态</h3><table><tr><th>目录</th><th>状态</th><th>说明</th></tr>';for(let o of j.offlineTasks){h+='<tr><td>'+esc(o.displayPath)+'</td><td>'+(o.ready?'<span class="oktxt">':'<span class="warn">')+esc(o.status)+'</span></td><td>'+esc(o.note)+'</td></tr>'}h+='</table>'}if(j.errors&&j.errors.length)h+='<p class="badtxt" style="margin:14px 0">'+j.errors.map(esc).join('<br>')+'</p>';if(j.items&&j.items.length){h+='<h3 style="font-size:14px;margin:16px 0 10px">命中的垃圾文件</h3><table><tr><th>文件</th><th>大小</th></tr>';for(let x of j.items){h+='<tr><td>'+esc(x.displayPath)+'</td><td>'+formatSize(x.size)+'</td></tr>'}h+='</table>'}else{h+='<div class="muted" style="margin-top:10px">未发现符合条件的垃圾文件</div>'}el('resultBox').innerHTML=h;loadLogs().catch(()=>{})}catch(e){toast(e.message,true);el('resultBox').innerHTML='<span class="badtxt">'+esc(e.message)+'</span>'}}
function formatSize(b){if(b<1024)return b+' B';if(b<1024*1024)return (b/1024).toFixed(1)+' KB';return (b/(1024*1024)).toFixed(1)+' MB'}
async function loadLogs(){let j=await api('/api/logs?_='+Date.now());el('logsBox').textContent=j.logs||''}async function clearLogs(){await api('/api/clear_logs',{method:'POST'});loadLogs();toast('日志已清空')}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=function(){document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));this.classList.add('active');document.querySelectorAll('section').forEach(s=>s.style.display='none');let id=this.dataset.tab;document.querySelectorAll('.card').forEach(c=>{if(c.id===id||(id==='config'&&c.id==='result'))c.style.display='block';else if(id==='browser'&&c.querySelector('.statusbox'))c.style.display='block';else if(id==='logs'&&c.id==='logs')c.style.display='block';else if(id==='result'&&c.id==='result')c.style.display='block'});if(id==='browser')listDir()});
el('saveBtn').onclick=()=>saveCfg().catch(e=>toast(e.message,true));el('testBtn').onclick=testConn;el('scanBtn').onclick=()=>scan(false);el('cleanBtn').onclick=()=>scan(true);el('listBtn').onclick=listDir;el('addCurrentBtn').onclick=()=>addTask(val('browsePath')||'/');el('addAllBtn').onclick=addAllTasks;el('clearTasksBtn').onclick=clearTasks;el('logsBtn').onclick=loadLogs;el('clearLogsBtn').onclick=clearLogs;
el('browsePath').addEventListener('keydown',e=>{if(e.key==='Enter')listDir()});
load().catch(e=>toast(e.message,true));
</script>
</body></html>`
